let songs = [
  {
    name: "Tabun たぶん INSTRUMENTAL",
    artist: "YOASOBI",
    img: "yoasobi",
    coverImg: "yoasobi",
    audio: "TABUN",
  },
  {
    name: "- 心海 - ",
    artist: "EVE",
    img: "josee",
    coverImg: "josee",
    audio: "SHINKAI",
  },
  {
    name: "-蒼のワルツ-",
    artist: "EVE",
    img: "AONOWALTZ",
    coverImg: "AONOWALTZ",
    audio: "special_AONOWALTZ",
  },
  {
    name: "- ファイトソング (Fight Song) -",
    artist: "EVE",
    img: "FIGHTSONG",
    coverImg: "FIGHTSONG",
    audio: "FIGHTSONG",
  },
  {
    name: "Bling Bang Bang Born",
    artist: "CREEPY NUTS",
    img: "mash",
    coverImg: "mash",
    audio: "BLINGBANGBORN",
  },
  {
    name: "「アイドル」",
    artist: "YOASOBI",
    img: "hoshino",
    coverImg: "hoshino",
    audio: "IDOL",
  },
  {
    name: "Akuma No Ko",
    artist: "Ai Higuchi",
    img: "AKUMANOKO",
    coverImg: "AKUMANOKO",
    audio: "special_AKUMANOKO",
  },
];
